- username: 'nil'
  alias: 'Luca Todesco'
  email: 'nil@exploit.rs'
  status: 'Looking a engineering job as a part-time'
  avatar: '../avatars/nil.png'
  is_public: true
  contacts:
    - kind: 'email'
      label: 'E-mail'
      id: 'nillability@protonmail.com'
      url: 'mailto:nillability@protonmail.com'
      quickly: true
    - kind: 'telegram'
      label: 'Telegram'
      id: 'unittype'
      url: 'https://t.me/unittype'
      quickly: true
    - kind: 'xmpp'
      label: 'XMPP'
      id: 'unsafe@xmpp.is'
      url: 'xmpp:unsafe@xmpp.is'
      quickly: true
    - kind: 'github'
      label: 'GitHub'
      id: 'nonnil'
      url: 'https://github.com/nonnil'
      quickly: true
    - kind: 'notabug'
      label: 'NotABug'
      id: 'nl'
      url: 'https://notabug.org/nl'
      quickly: false

- username: 'power'
  alias: 'Power'
  email: 'power@exploit.rs'
  status: 'medical'
  is_public: true
  avatar: '../avatars/nil.png'
- username: 'exploit.rs'
  alias: 'Exploit.RS'
  email: 'me@exploit.rs'
  status: 'Bot'
  is_public: true
  avatar: '../avatars/nil.png'