- username: 'nil'
  alias: 'Luca Todesco'
  bio: 'Looking a engineering job as a part-time'
  avatar: '../avatars/nil.png'
  location: 'Tokyo ⇄ Cyberia'
  org: ''
  company: ''
  education: 'Keio Uni'
  is_public: true
  contacts:
    - kind: 'email'
      label: 'E-mail'
      id: 'nillability@protonmail.com'
      url: 'mailto:nillability@protonmail.com'
      quickly: true
    - kind: 'telegram'
      label: 'Telegram'
      id: 'unittype'
      url: 'https://t.me/unittype'
      quickly: true
    - kind: 'xmpp'
      label: 'XMPP'
      id: 'unsafe@xmpp.is'
      url: 'xmpp:unsafe@xmpp.is'
      quickly: true
    - kind: 'github'
      label: 'GitHub'
      id: 'nonnil'
      url: 'https://github.com/nonnil'
      quickly: true
    - kind: 'notabug'
      label: 'NotABug'
      id: 'nl'
      url: 'https://notabug.org/nl'
      quickly: false
  skills:
    - kind: 'programming'
      languageKind: 'rust'
      label: 'Rust'
      description: 'Most favourite programming language.'
    - kind: 'programming'
      languageKind: 'nim'
      label: 'Nim'
      description: 'Most writable programming language.'
    - kind: 'programming'
      languageKind: 'elm'
      label: 'Elm'
      description: 'My hobby.'
    - kind: 'programming'
      languageKind: 'go'
      label: 'Go'
      description: 'Easier than Nim, maybe.'
    - kind: 'programming'
      languageKind: 'typescript'
      label: 'TypeScript'
      description: 'Use in Front-end'
    - kind: 'security'
      approach: 'penetest'
      label: 'Penetration test'
      description: 'I have reported several vulnerabilities to companies...'
    - kind: 'security'
      approach: 're'
      label: 'Reverse Engineering'
      description: 'Noobie.'

- username: 'power'
  alias: 'Power'
  email: 'power@exploit.rs'
  status: 'medical'
  is_public: true
  avatar: '../avatars/nil.png'
- username: 'exploit.rs'
  alias: 'Exploit.RS'
  email: 'me@exploit.rs'
  status: 'Bot'
  is_public: true
  avatar: '../avatars/nil.png'