- username: 'nil'
  alias: 'John Paul'
  bio: 'Looking for a part-time engineering job.'
  avatar: '../avatars/nil.png'
  location: 'Tokyo ⇄ The Wired'
  exploitrs: 'nil'
  org: ''
  company: ''
  education: 'Keio University'
  is_public: true
  contacts:
    - kind: 'email'
      label: 'E-mail'
      id: 'nil@exploit.rs'
      url: 'mailto:nil@exploit.rs'
      quickly: true
    - kind: 'telegram'
      label: 'Telegram'
      id: 'unittype'
      url: 'https://t.me/unittype'
      quickly: true
    - kind: 'xmpp'
      label: 'XMPP'
      id: 'unsafe@xmpp.is'
      url: 'xmpp:unsafe@xmpp.is'
      quickly: true
    - kind: 'github'
      label: 'GitHub'
      id: 'nonnil'
      url: 'https://github.com/nonnil'
      quickly: true
    - kind: 'discord'
      label: 'Discord'
      id: '@0100.0001'
      url: 'https://discordlookup.com/user/693368957213605929'
      quickly: false
    - kind: 'notabug'
      label: 'NotABug'
      id: 'nl'
      url: 'https://notabug.org/nl'
      quickly: false
  skills:
    - kind: 'programming'
      languageKind: 'rust'
      label: 'Rust'
      description: 'My favourite programming language.'
    - kind: 'programming'
      languageKind: 'nim'
      label: 'Nim'
      description: 'My best programming language to write in.'
    - kind: 'programming'
      languageKind: 'elm'
      label: 'Elm'
      description: 'My hobby.'
    - kind: 'programming'
      languageKind: 'go'
      label: 'Go'
      description: 'Easier than Nim, maybe.'
    - kind: 'programming'
      languageKind: 'typescript'
      label: 'TypeScript'
      description: 'Used for Front-end'
    - kind: 'security'
      approach: 'pentest'
      label: 'Penetration test'
      description: 'I have reported several vulnerabilities to companies...'
    - kind: 'security'
      approach: 're'
      label: 'Reverse Engineering'
      description: 'I am interested in malware analysis.'

- username: 'power'
  alias: 'Nagax'
  bio: 'Nagaxニャン'
  is_public: true
  avatar: '../avatars/power.jpeg'
  location: 'Darkness'
  education: 'Nursing School'
  org: ''
  company: ''
  contacts:
    - kind: 'telegram'
      label: 'Telegam'
      id: 'xxnagaxx'
      url: 'https://t.me/xxnagaxx'
      quickly: true
  
- username: mohammad
  alias: 'Mohammad'
  bio: 'Certified Ethical Hacker'
  is_public: true
  avatar: '../avatars/default.jpg'
  contacts:
    - kind: 'telegram'
      label: 'Telegram'
      id: ''
      url: ''
      quickly: true

- username: 'exploit.rs'
  alias: 'Exploit.RS'
  status: 'Bot'
  is_public: false
  avatar: '../avatars/default.jpg'

- username: 'exploit.rs'
  alias: 'Exploit.RS'
  status: 'Bot'
  is_public: false
  avatar: '../avatars/default.jpg'

- username: 'exploit.rs'
  alias: 'Exploit.RS'
  status: 'Bot'
  is_public: false
  avatar: '../avatars/default.jpg'