- username: 'nil'
  alias: 'Luca Todesco'
  email: 'nil@exploit.rs'
  status: 'Looking a engineering job as a part-time'
  avatar: '../avatars/nil.png'
  is_public: true
  contacts:
    - kind: 'telegram'
      label: 'Telegram'
      id: 'unittype'
      url: 'https://t.me/unittype'
      quickly: true
    - kind: 'github'
      label: 'Telegram'
      id: 'unittype'
      url: 'https://t.me/unittype'
      quickly: true
    - kind: 'noabug'
      label: 'NotABug'
      id: 'nulled'
      url: 'https://notabug.org/nulled'
      quickly: false

- username: 'power'
  alias: 'Power'
  email: 'power@exploit.rs'
  status: 'medical'
  is_public: true
  avatar: '../avatars/nil.png'
- username: 'exploit.rs'
  alias: 'Exploit.RS'
  email: 'me@exploit.rs'
  status: 'Bot'
  is_public: true
  avatar: '../avatars/nil.png'